// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

function $$eval(_param) {
  while(true) {
    var param = _param;
    switch (param.tag | 0) {
      case 0 : 
          return param[0];
      case 1 : 
          return $$eval(param[0]) + $$eval(param[1]);
      case 2 : 
          return $$eval(param[0]) - $$eval(param[1]);
      case 3 : 
          return $$eval(param[0]) * $$eval(param[1]);
      case 4 : 
          return $$eval(param[0]) / $$eval(param[1]);
      case 5 : 
          _param = param[0];
          continue ;
      
    }
  };
}

function getBlanks(indent) {
  return " ".repeat((indent << 1));
}

function getLine(indent, input) {
  return getBlanks(indent).concat(input);
}

function print_(indent, input) {
  switch (input.tag | 0) {
    case 0 : 
        var input$1 = "Number(" + (Pervasives.string_of_float(input[0]) + ")");
        console.log(getBlanks(indent).concat(input$1));
        return /* () */0;
    case 1 : 
        console.log(getBlanks(indent).concat("Add("));
        print_(indent + 1 | 0, input[0]);
        console.log(getBlanks(indent).concat(","));
        print_(indent + 1 | 0, input[1]);
        console.log(getBlanks(indent).concat(")"));
        return /* () */0;
    case 2 : 
        console.log(getBlanks(indent).concat("Minus("));
        print_(indent + 1 | 0, input[0]);
        console.log(getBlanks(indent).concat(","));
        print_(indent + 1 | 0, input[1]);
        console.log(getBlanks(indent).concat(")"));
        return /* () */0;
    case 3 : 
        console.log(getBlanks(indent).concat("Multiply("));
        print_(indent + 1 | 0, input[0]);
        console.log(getBlanks(indent).concat(","));
        print_(indent + 1 | 0, input[1]);
        console.log(getBlanks(indent).concat(")"));
        return /* () */0;
    case 4 : 
        console.log(getBlanks(indent).concat("Divid("));
        print_(indent + 1 | 0, input[0]);
        console.log(getBlanks(indent).concat(","));
        print_(indent + 1 | 0, input[1]);
        console.log(getBlanks(indent).concat(")"));
        return /* () */0;
    case 5 : 
        console.log(getBlanks(indent).concat("("));
        print_(indent + 1 | 0, input[0]);
        console.log(getBlanks(indent).concat(")"));
        return /* () */0;
    
  }
}

function print(expr) {
  return print_(0, expr);
}

exports.$$eval = $$eval;
exports.getBlanks = getBlanks;
exports.getLine = getLine;
exports.print_ = print_;
exports.print = print;
/* No side effect */
